### ISSUE TITLE
Gtk window doesn't open for the second time.

### ISSUE THREAD

**Issue by akhilesh-k** [anshulgupta0803/iitb-internet-login#1]
When i tried to test the code in terminal, no window would appear after I saved preference for the first time.<br>I am doing wrong way, or is there some bug in program. Recently in one of my code containing Gtk window, I faced the same problem.<br>I refered [stackoverflow](http://stackoverflow.com/questions/32597515/pygtk-cant-open-the-same-window-twice), it said I need to hide window.

**Comment by anshulgupta0803** [comment]
It is intended to work that way. The application checks whether the credentials are already stored or not. If stored, it directly proceeds by showing the indicator and functions normally, otherwise it prompts the user to enter the credentials by showing the Preferences dialog box. You can open the preferences dialog box by opening the menu on the indicator and choosing **Preferences...**
